version: '3.8'

services:
  # MySQL 服务配置
  mysql:
    # 使用你上传到 Docker Hub 的自定义 MySQL 镜像
    image: king210319/code-webapp-mysql:5.7-custom  
    environment:
      MYSQL_ROOT_PASSWORD: root        # root 用户密码
      MYSQL_DATABASE: studentinfomanagement  # 自动创建的数据库名
    volumes:
      # 挂载初始化脚本到 MySQL 自动执行目录
      - ./ddl.sql:/docker-entrypoint-initdb.d/init.sql  
      # 持久化存储 MySQL 数据（可选，避免容器删除后数据丢失）
      - mysql_data:/var/lib/mysql      
    ports:
      - "3307:3306"  # 宿主机端口:容器端口，可根据需求调整
    # 确保字符集正确（若镜像未内置配置，可在此补充）
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Web 应用服务配置
  webapp:
    # 使用你上传到 Docker Hub 的 Web 应用镜像
    image: king210319/code-webapp:latest  
    depends_on:
      - mysql  # 确保 MySQL 启动后再启动 Web 应用
    ports:
      - "8080:8080"  # 宿主机端口:容器端口，映射 Web 应用端口
    environment:
      # 配置数据库连接（需与 MySQL 服务名、数据库名匹配）
      DB_URL: jdbc:mysql://mysql:3306/studentinfomanagement?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      DB_USER: root          # MySQL 用户名
      DB_PASSWORD: root      # MySQL 密码

# 持久化存储卷（可选，用于保存 MySQL 数据）
volumes:
  mysql_data:
