name: Run Project with Docker Compose
# 触发条件，这里配置成手动触发，你也可以根据需求改成 push 到特定分支等自动触发
on:
  workflow_dispatch:  

jobs:
  run-compose:
    # 运行环境，使用最新的 Ubuntu 系统
    runs-on: ubuntu-latest  
    steps:
      # 第一步：检出仓库代码，这样才能获取到仓库里的 docker-compose.yml 文件
      - name: Checkout repository code
        uses: actions/checkout@v4  

      # 第二步：登录到 Docker Hub，因为要拉取你上传的私有镜像（如果是公开镜像，这一步也可保留规范流程）
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     # 这里使用 GitHub Secrets 中配置的 Docker Hub 用户名，需要你提前在仓库 Secrets 里设置好 DOCKER_HUB_USERNAME
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}  
      #     # 同理，DOCKER_HUB_PASSWORD 也是提前在 Secrets 里配置的 Docker Hub 访问令牌或密码
      #     password: ${{ secrets.DOCKER_HUB_PASSWORD }}  

      # 第三步：拉取所需的 Docker 镜像，确保本地有这两个镜像用于后续启动
      - name: Pull necessary Docker images
        run: |
          docker pull king210319/code-webapp:latest
          docker pull king210319/code-webapp-mysql:5.7-custom

      # 使用正确的 Docker Compose 动作版本（推荐 v2 或具体版本）
      - name: Set up Docker Compose
        uses: docker/compose-action@v2  # 使用 major 版本，自动更新

      # 第四步：使用 docker-compose 启动服务并在后台保持运行
      - name: Start services with Docker Compose
        run: |
          # 因为编排文件是 docker-compose.yml，所以直接用默认的命令即可
          docker-compose up -d  
